Fix: Branch Param As String
Branches should always be a `string`, otherwise tags like `21.12`
are parsed as floats, which leads to errors such as:
```
  File "regression_testing/repo.py", line 38, in get_branch_name
    return self.branch_wanted.strip("\"")
AttributeError: 'float' object has no attribute 'strip'
```